version: "3"

services:
 mysql:
  platform: linux/x86_64
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_DATABASE: 'theeduke_edu'
    # So you don't have to use root, but you can if you like
    MYSQL_USER: 'theeduke_theedukey'
    # You can use whatever password you like
    MYSQL_PASSWORD: 'theedukeytheedukeytheedukey'
    # Password for root access
    MYSQL_ROOT_PASSWORD: 'theedukeytheedukeytheedukey'
  ports:
    # <Port exposed> : < MySQL Port running inside container>
    - '3307:3306'